In [1]:
import pandas as pd

In [2]:
imdb_top_250_df = pd.read_csv('Resources/IMDB_cleaned_Top_250.csv')
lead_actor_actress_df = pd.read_csv('Resources/Lead_actor_actress_nominees.csv')
supporting_actor_actress_nominees_df = pd.read_csv('Resources/Supporting_actor_actress_nominees.csv')
series_nominees_df = pd.read_csv('Resources/Series_nominees.csv')
winners_df = pd.read_csv('Resources/Winners_cleaned_2010-2022.csv')

In [3]:
def get_title_category_list(df, title_column, category_column):
    title_category = []
    for index, row in df.iterrows():
        dict = {}
        dict['title'] = row[title_column]
        dict['category'] = row[category_column]
        title_category.append(dict)
        
    return list(title_category)

In [4]:
title_category = []

for index, row in imdb_top_250_df.iterrows():
    for category in row['Genre'].strip().split(', '):
        dict = {}
        dict['title'] = row['Titles']
        dict['category'] = category
        title_category.append(dict)

title_category.extend(get_title_category_list(lead_actor_actress_df, 'Titles', 'Category'))     
title_category.extend(get_title_category_list(supporting_actor_actress_nominees_df, 'Titles', 'Category'))
title_category.extend(get_title_category_list(series_nominees_df, 'Titles', 'Category'))

for index, row in winners_df.iterrows():
    dict = {}

    title_category.append({ 'title': row['Comedy'], 'category':'Comedy' })
    title_category.append({ 'title': row['Drama'], 'category':'Drama' })
    title_category.append({ 'title': row['Lead Comedy Actor(Title)'], 'category':'Comedy' })
    title_category.append({ 'title': row['Lead Drama Actor(Title)'], 'category':'Drama' })
    title_category.append({ 'title': row['Lead Comedy Actress(Title)'], 'category':'Comedy' })
    title_category.append({ 'title': row['Lead Drama Actress(Title)'], 'category':'Drama' })

title_category_df = pd.DataFrame(title_category).drop_duplicates()
title_category_df

                 title   category
0         Breaking Bad      Crime
1         Breaking Bad      Drama
2         Breaking Bad   Thriller
3      Game of Thrones     Action
4      Game of Thrones  Adventure
...                ...        ...
1537       Mrs. Maisel     Comedy
1543    Bridge Fleabag     Comedy
1554  Connor The Crown      Drama
1555       Smart Hacks     Comedy
1556            Colman      Drama

[782 rows x 2 columns]

In [5]:
category_df = pd.read_csv('output/categories.csv')
titles_df = pd.read_csv('output/titles.csv')

title_category_df = title_category_df.merge(category_df, left_on='category', right_on='Category', how='left')

title_category_df = title_category_df.merge(titles_df, left_on='title', right_on='Titles', how='left')

title_category_df = title_category_df[['title_id', 'category_id']]
title_category_df.head()

title_category_df.to_csv('output/title_categories.csv', index=False)